# Generated by Django 3.0.5 on 2020-04-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Тут должно быть Имя', max_length=30, verbose_name='Имя')),
                ('surdname', models.CharField(max_length=30)),
                ('otch', models.CharField(max_length=30)),
                ('borndate', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phonenum', models.CharField(max_length=11)),
                ('startworkdate', models.DateTimeField()),
                ('endworkdate', models.DateTimeField(blank=True, null=True)),
                ('jobtitle', models.CharField(max_length=30)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intest.Department')),
            ],
        ),
    ]
