# Generated by Django 3.0.5 on 2020-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intest', '0002_auto_20200419_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='borndate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='endworkdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='startworkdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
