# Generated by Django 3.0.5 on 2020-04-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intest', '0003_auto_20200420_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-surname']},
        ),
    ]
